# -*- coding: utf-8 -*-
"""Plotly_Programming.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SK_7Y5JludLeMQvZCA2v0rBwwv150B_4
"""

import plotly.graph_objects as go

fig = go.Figure()
fig.add_trace(go.Scatter(x=[1,2,3,5,6], y=[4,5,6,7,8] , mode ='markers'))
fig.show()

fig = go.Figure()
fig.add_trace(go.Scatter(x=[1,2,3,5,6], y=[4,5,6,7,8] , mode ='lines'))
fig.show()

fig = go.Figure()
fig.add_trace(go.Bar(x=[1,2,3,5,6], y=[4,5,6,7,8]))
fig.show()

x = [1,21,23,25,66,2,15,45,4,21,21,54,5,42,12,11,54]

fig = go.Figure(data = [go.Histogram(x = x)])
fig.show()

import seaborn as sns

tips_data = sns.load_dataset("tips")

tips_data

fig = go.Figure(data = [go.Histogram(x =tips_data.total_bill)])
fig.show()

fig = go.Figure()
fig.add_trace(go.Scatter(x=tips_data.total_bill, y=tips_data.tip, mode ='markers'))
fig.show()

fig = go.Figure()
fig.add_trace(go.Scatter(x=tips_data.total_bill, y=tips_data.tip, mode ='markers',marker_size = 10*tips_data["size"]))
fig.show()

fig = go.Figure()
fig.add_trace(go.Scatter3d(x=tips_data.total_bill, y=tips_data.tip, mode ='markers',z= 10*tips_data["size"]))
fig.show()

fig = go.Figure()
fig.add_trace(go.Scatter3d(x=[1,2,3,4,5], y=[2,3,4,5,6], mode ='lines',z= [2,3,4,2]))
fig.show()

fig = go.Figure()
fig.add_trace(go.Scatter3d(x=[1,2,3,4,5], y=[2,3,4,5,6], mode ='markers',z= [2,3,4,2]))
fig.show()

fig = go.Figure()
fig.add_trace(go.Scatter3d(x=tips_data.total_bill, y=tips_data.tip, mode ='lines',z= 10*tips_data["size"]))
fig.show()

